Add bind-timeout option to let eggdrop wait for useable listen port
eggheads/eggdrop pull request #1143
Opened 2021-03-11 21:08 UTC by michaelortmann

Found by:
Patch by: michaelortmann
Fixes: 

One-line summary:
Workaround and/or solution to #1142

Additional description (if needed):
We removed the port+0..4 logic for eggdrop 1.9. This PR adds a new logic, that lets eggdrop wait for an unreleased port by a configureable amount of seconds.

Test cases demonstrating functionality (if applicable):
For the following test i blocked the listen port for 2 seconds:
```
$ grep bind-timeout BotA.conf 
set bind-timeout 5
```

```
$ ./eggdrop -n BotA.conf
[...]
[22:04:48] The specified address is already in use. Attempting to bind for 5 seconds.
[22:04:50] Listening for telnet connections on 0.0.0.0 port 3333 (all).
```

2021-03-12 14:54 UTC, MalaGaM commented
Very good idea. The only negative point may be the name *bind-timeout-. because *bind* reminds me of a lot of things in eggdrop except the port listen. this is an unclear name for the listen timeout. I suggest instead *listen-timeout*?

2021-03-18 00:47 UTC, michaelortmann commented
Geo, thommey: what do you think about `listen-timeout`?

2021-03-18 08:02 UTC, MalaGaM requested changes
https://github.com/eggheads/eggdrop/pull/1143#issuecomment-797539947

Rename bind-timeout to listen-timeout

2021-10-07 21:00 UTC, vanosg commented
I don't think this feature would be used much, if at all. If a port isn't available at time X, it likely still wouldn't be available at time X+5 (or whatever the timeout is set to). At this time, I'm not in favor of adding such a feature

2022-06-04 19:59 UTC, closed without merging

2022-06-04 20:19 UTC, thommey commented
I don't think this needs to be an option. The only case where the socket is blocked is if you restart eggdrop very quickly and the OS still blocks it, which is really quick and a sleep(1) should cover that, no? Or what problem are we trying to solve? Can it be solved with SO_REUSEADDR or SO_REUSEPORT?