(WIP) Add server list Tcl command
eggheads/eggdrop pull request #1200
Opened 2021-09-07 22:07 UTC by vanosg

Found by:
Patch by:
Fixes: 

One-line summary:
Add server list Tcl command

Additional description (if needed):
Adds server list command (similar to server add/server remove), returns a list of all servers added to the bot as a list of lists; in the format {{host} {port} {password}}. The port will have a + prepended if it is an SSL-enabled port

Test cases demonstrating functionality (if applicable):

2021-09-09 18:34 UTC, skralg commented
lgtm

2021-09-13 23:06 UTC, MalaGaM requested changes

2021-09-13 23:06 UTC, ZarTek-Creole commented on src/mod/server.mod/tclserv.c
>          ". Should be \"add\" or \"remove\"", NULL);
". Should be \"add\" \"list\" or \"remove\"", NULL);

2021-09-14 19:51 UTC, MalaGaM commented
Possibly related to  #1131 ?

2021-09-26 14:03 UTC, vanosg commented
@MalaGaM I can't tell- please, VERY CONCISELY, summarize 1131 in that thread. It talks about a lot of things that don't have to do with the title. In one or two sentences, in that issue, please summarize what the single issue is that you are hoping to address

2021-09-26 16:48 UTC, MalaGaM commented
> @MalaGaM I can't tell- please, VERY CONCISELY, summarize 1131 in that thread. It talks about a lot of things that don't have to do with the title. In one or two sentences, in that issue, please summarize what the single issue is that you are hoping to address

I think it's correct like this. The other thread ( #1131) talks about $::servers. I thought I had covered the "server list" in the thread, but it was discussed on irc and you had implemented it in the code. Good work :-)

LGTM

2021-09-27 01:42 UTC, vanosg commented
I'll self-invoke thommey... should this include server name, and should this be a dict, to allow for future extension? I already think I know the answer to this, but I'll wait for thommey to say it... :)

2021-11-27 15:41 UTC, thommey commented on src/mod/server.mod/tclserv.c
> +  BADARGS(2, 5, " subcommand host ?port ?password??");
now that host is optional (server list), it should be ?host?

2021-11-27 16:05 UTC, merged