(WIP) change configure to make tdns default
eggheads/eggdrop pull request #1224
Opened 2021-11-06 21:44 UTC by michaelortmann

Found by:
Patch by: michaelortmann
Fixes: #1221

One-line summary:

Additional description (if needed):

Test cases demonstrating functionality (if applicable):

2021-11-28 02:20 UTC, vanosg commented
main.c line 520 needs to remove 'beta'

2021-11-28 02:22 UTC, vanosg commented
chanprog.c; two instances around line 375 need 'beta' removed also

2021-11-28 05:08 UTC, michaelortmann commented
> main.c line 520 needs to remove 'beta'

done

2021-11-28 05:08 UTC, michaelortmann commented
> chanprog.c; two instances around line 375 need 'beta' removed also

done.

2021-12-02 13:19 UTC, vanosg requested changes
We need to clean up the config file to properly reflect this change... I can do that if you like

2021-12-02 18:12 UTC, michaelortmann commented
> We need to clean up the config file to properly reflect this change... I can do that if you like

Yes, that would be nice of you :)

2021-12-18 16:09 UTC, merged