Replace deprecated / obsolete gethostbyname2() with POSIX.1-2001 getaddrinfo()
eggheads/eggdrop pull request #1348
Opened 2022-11-15 18:11 UTC by michaelortmann

Found by: michaelortmann
Patch by: michaelortmann
Fixes: 

One-line summary:
Replace deprecated / obsolete gethostbyname2() with POSIX.1-2001 getaddrinfo()

Additional description (if needed):
Please run **misc/runautotools** and **misc/makedepend**

Additionally, this PR will enhance debug logging, example:
`[19:00:56] net: setsockname(): getaddrinfo(): hostname virtual.host.com not known`
with `set vhost4 "virtual.host.com"`

Test cases demonstrating functionality (if applicable):

2022-12-19 15:39 UTC, thommey requested changes

2022-12-19 15:39 UTC, thommey commented on src/net.c
> +          if (res == res0 || res->ai_family == (pref_af ? AF_INET6 : AF_INET)) {
AF_INET6 might be undefined on systems without ipv6 support

2022-12-19 16:09 UTC, michaelortmann commented on src/net.c
> +          if (res == res0 || res->ai_family == (pref_af ? AF_INET6 : AF_INET)) {
yes. but i didnt change the visibility of the AF_INET6 usage here, see old code:

https://github.com/eggheads/eggdrop/pull/1348/files#diff-e83dab64ed96e8a50f94260f6a3dea5712ef4150a7c2aa3c1c282d4227c93b66L179

additionally i tested compiling eggdrop with `--disable-ipv6`

2022-12-30 21:33 UTC, vanosg commented
@michaelortmann , while we wait for @thommey , can you resolve conflicts? Thanks!

2023-02-12 21:25 UTC, vanosg commented
@michaelortmann can you take a look at the compile error we have here?

2023-02-14 00:19 UTC, merged