Fix logging of QUIT msg
eggheads/eggdrop pull request #1488
Opened 2023-10-14 21:30 UTC by michaelortmann

Found by: michaelortmann
Patch by: michaelortmann
Fixes: 

One-line summary:
Log QUIT msg like we alrteady do for any other msg sent to the server.

Additional description (if needed):
Messages from eggdrop to irc server are logged when raw-log is set. depending on the queue the message was put in, it gets logged like for example `[m->]` or `[s->]` The Quit message was sent to server directly without using those queues and thus was not logged.

Test cases demonstrating functionality (if applicable):
in eggdrop.conf `set raw-log 1`
```
.die
[23:29:24] tcl: builtin dcc call: *dcc:die -HQ 1 
[23:29:24] #-HQ# die 
[23:29:24] [->] QUIT :-HQ
```

2023-12-30 17:42 UTC, thommey requested changes
I know it was there before but `quit_msg[0] ? quit_msg : ""` seems pointless, `quit_msg` is the same.
Otherwise LGTM

2024-01-03 22:25 UTC, michaelortmann commented
> I know it was there before but `quit_msg[0] ? quit_msg : ""` seems pointless, `quit_msg` is the same. Otherwise LGTM

good find, cleanup done.

2024-01-03 23:22 UTC, vanosg approved these changes

2024-01-03 23:24 UTC, vanosg approved these changes

2024-01-03 23:28 UTC, merged