Fix bot_away()
eggheads/eggdrop pull request #1547
Opened 2024-03-16 09:11 UTC by michaelortmann

Found by: michaelortmann
Patch by: michaelortmann
Fixes: 

One-line summary:
Check return value of `partyidx`

Additional description (if needed):
Found by botnet fuzzing combined with `-fsanitize=address`

Test cases demonstrating functionality (if applicable):

2024-05-05 15:25 UTC, vanosg commented
Can we address the FIXMEs before we merge?

2024-05-09 00:43 UTC, michaelortmann commented
First FIXME got fixed.

Second FIXME was separated / replaced by the more general #1583

2025-03-23 19:05 UTC, thommey requested changes

2025-03-23 19:05 UTC, thommey commented on src/botcmd.c
> +    if (i > ((INT_MAX >> 6) - j)) /* if overflow return -1 */
INT_MAX >> 6 smells like UD because it overflows int, no?, the old way was better if that's the case

2025-06-04 12:42 UTC, thommey requested changes

2025-06-04 12:42 UTC, thommey commented on src/mod/assoc.mod/assoc.c
> +      dprintf(LOG_DEBUG, "ASSOC: Channel number outside bounds 0..%i\n", GLOBAL_CHANS);
undo this one change pls, then it's good (removing braces is the opposite of code style guidelines)

2025-06-04 21:33 UTC, michaelortmann commented on src/mod/assoc.mod/assoc.c
> +      dprintf(LOG_DEBUG, "ASSOC: Channel number outside bounds 0..%i\n", GLOBAL_CHANS);
absolutely right. done.

2025-06-04 23:29 UTC, merged