Fix read_lang() crash on malformed language file
eggheads/eggdrop pull request #1681
Opened 2024-08-27 21:56 UTC by michaelortmann

Found by: michaelortmann
Patch by: michaelortmann
Fixes: 

One-line summary:
Fix read_lang() crash on malformed language file

Additional description (if needed):
eggdrop crashes on malformed (missing `,`) language file
Example:
Edit `language/core.english.lang`
Change (remove `,`)
`0x132,inactive`
Into
`0x132inactive`
```
$ ./eggdrop -t BotA.conf 
* Please report problem to https://github.com/eggheads/eggdrop/issues
* Check doc/BUG-REPORT on how to do so.
Segmentation fault (core dumped)
```

While fixing the parser to not crash, memory allocation also got optimized.
Before:
```
$ ltrace ./eggdrop -t BotA.conf 2>&1|grep realloc|wc -l
.die
686
```
After:
```
$ ltrace ./eggdrop -t BotA.conf 2>&1|grep realloc|wc -l
.die
75
```

Test cases demonstrating functionality (if applicable):

2025-02-23 20:50 UTC, thommey commented on src/language.c
> +        strcpy(ltext, strchr(lbuf, ',') + 1);
why isn't the 2nd argument just ctmp?

2025-02-23 23:45 UTC, michaelortmann commented on src/language.c
> +        strcpy(ltext, strchr(lbuf, ',') + 1);
you mean `ctmp + 1` (stripping the leading comma). ty, simplified that one.

2025-03-23 19:21 UTC, thommey requested changes

2025-03-23 19:21 UTC, thommey commented on src/language.c
> +      strcat(ltext, lbuf);
strcat, really? :)

2025-03-23 21:00 UTC, michaelortmann commented on src/language.c
> +      strcat(ltext, lbuf);
better than what came before : strcpy(strchr(ltext, 0), lbuf);
haha.
but you are right, why not go then extra mile and do it really proper.

2025-03-23 21:36 UTC, michaelortmann commented on src/language.c
> +      strcat(ltext, lbuf);
Fixed.

2025-06-04 15:31 UTC, thommey approved these changes

2025-06-04 15:33 UTC, thommey commented
I assume  you tested this under valgrind with all our current lang files :)

2025-06-04 23:24 UTC, merged