Fix jump server name and pass len handling
eggheads/eggdrop pull request #1725
Opened 2024-12-23 08:31 UTC by michaelortmann

Found by: michaelortmann
Patch by: michaelortmann
Fixes: 

One-line summary:

Additional description (if needed):

Test cases demonstrating functionality (if applicable):
`/msg BotA jump hunter2 aaaaaaaaaabbbbbbbbbbaaaaaaaaaabbbbbbbbbbaaaaaaaaaabbbbbbbbbbaaaaaaaaaabbbbbbbbbbaaaaaaaaaabbbbbbbbbbaaaaaaaaaaabbbbbbbbbba.edu`

```
[08:27:50] [@] :testuser!~michael@localhost PRIVMSG BotA :jump hunter2 aaaaaaaaaabbbbbbbbbbaaaaaaaaaabbbbbbbbbbaaaaaaaaaabbbbbbbbbbaaaaaaaaaabbbbbbbbbbaaaaaaaaaabbbbbbbbbbaaaaaaaaaaabbbbbbbbbba.edu
[08:27:50] pbkdf2 method SHA256 rounds 16000, user 10.718ms sys 6.447ms
[08:27:50] (testuser!~michael@localhost) !testuser! JUMP aaaaaaaaaabbbbbbbbbbaaaaaaaaaabbbbbbbbbbaaaaaaaaaabbbbbbbbbbaaaaaaaaaabbbbbbbbbbaaaaaaaaaabbbbbbbbbbaaaaaaaaaaabbbbbbbbbba.edu 6667 
=================================================================
==28916==ERROR: AddressSanitizer: global-buffer-overflow on address 0x78eb664f6b79 at pc 0x78eb69ef6a02 bp 0x7ffdedec78b0 sp 0x7ffdedec7058
WRITE of size 127 at 0x78eb664f6b79 thread T0
    #0 0x78eb69ef6a01 in strcpy /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_interceptors.cpp:563
    #1 0x78eb64d84943 in msg_jump .././irc.mod/msgcmds.c:1098
[...]
```

2025-01-20 20:38 UTC, thommey requested changes

2025-01-20 20:38 UTC, thommey commented on src/mod/server.mod/servmsg.c
> +  char pass[sizeof newserverpass], botserver[sizeof newserver], s[1024];
prefer the defines here, newserverpass could be `extern char *` or `extern char[]` and then sizeof would be wrong

2025-01-20 21:31 UTC, michaelortmann commented on src/mod/server.mod/servmsg.c
> +  char pass[sizeof newserverpass], botserver[sizeof newserver], s[1024];
Done.

2025-02-02 13:40 UTC, thommey approved these changes

2025-02-23 20:39 UTC, thommey approved these changes

2025-02-23 20:40 UTC, merged