Gotinvite strncpyz
eggheads/eggdrop pull request #567
Opened 2018-08-21 18:40 UTC by michaelortmann

Found by: michaelortmann
Patch by: michaelortmann
Fixes: enhancement only patch

One-line summary:
gotinvite should use strncpyz here. introduce CHANNELLEN.

Additional description (if needed):
we had some irc discussion about #3 and #38, this patch here should be fine as is.

Test cases demonstrating functionality (if applicable):
i startet eggdrop, invited it to a +i channel and it worked fine.

2018-08-22 22:40 UTC, Cizzle commented
LGTM, though there's still a lot more places with the hardcoded 81.

2018-08-23 00:52 UTC, michaelortmann commented
i did some more places.
enough for now.
because i fear, if i did even more, this pull request would become too bloated to be merged.

2018-08-23 01:14 UTC, michaelortmann commented
i did some more places.
enough for now.
because i fear, if i did even more, this pull request would become too bloated to be merged.

2018-10-08 20:31 UTC, Cizzle commented
LGTM

2018-10-09 04:49 UTC, vanosg commented
build

2018-10-09 08:49 UTC, Cizzle requested changes

2018-10-09 08:49 UTC, Cizzle commented on src/mod/channels.mod/tclchan.c
> +    strncpyz(chan->dname, newname, sizeof chan->dname);
`strlcpy`

2018-10-09 08:49 UTC, Cizzle commented on src/mod/channels.mod/userchan.c
> +    strncpyz(ch->channel, chname, sizeof ch->channel);
`strlcpy`

2018-10-09 08:49 UTC, Cizzle commented on src/mod/irc.mod/chan.c
> +  strncpyz(last_invchan, msg, sizeof last_invchan);
`strlcpy`

2018-10-09 08:49 UTC, Cizzle commented on src/mod/irc.mod/chan.c
> +          strncpyz(chan->name, chname, sizeof chan->name);
`strlcpy`

2018-10-09 09:13 UTC, michaelortmann commented on src/mod/channels.mod/tclchan.c
> +    strncpyz(chan->dname, newname, sizeof chan->dname);
resolved

2018-10-09 09:14 UTC, michaelortmann commented on src/mod/channels.mod/userchan.c
> +    strncpyz(ch->channel, chname, sizeof ch->channel);
resolved

2018-10-09 09:14 UTC, michaelortmann commented on src/mod/irc.mod/chan.c
> +  strncpyz(last_invchan, msg, sizeof last_invchan);
resolved

2018-10-09 09:14 UTC, michaelortmann commented on src/mod/irc.mod/chan.c
> +          strncpyz(chan->name, chname, sizeof chan->name);
resolved

2018-10-09 09:17 UTC, michaelortmann commented
@Cizzle: requested changes were done.

2018-10-09 09:28 UTC, Cizzle approved these changes

2018-10-13 02:04 UTC, vanosg commented
build

2018-10-13 02:06 UTC, merged