implement first prototype
eggheads/eggdrop pull request #570
Opened 2018-08-22 04:03 UTC by michaelortmann

Found by: saapete
Patch by: michaelortmann
Fixes: #201

One-line summary:
add debug log for (some) triggered binds

Additional description (if needed):
this is only a first implementation prototype
now i wait for feedback from you eggheads, see also my comment to #201

Test cases demonstrating functionality (if applicable):
> ./eggdrop -ntm
[...]
.console +d
[...]
[05:50:38] triggered bind *dcc:console total time = 0.036ms
[05:50:51] triggered bind *raw:311 begin
[05:50:51] triggered bind *raw:311 total time = 0.015ms
[05:50:51] triggered bind *raw:318 begin
[05:50:51] triggered bind *raw:318 total time = 0.004ms
[05:50:54] triggered bind *raw:irc:join begin
[05:50:54] triggered bind *join:notes begin
[05:50:54] triggered bind *join:notes total time = 0.006ms
[05:50:54] fix377 joined #bar.
[05:50:54] triggered bind *raw:irc:join total time = 0.136ms
[05:50:54] triggered bind *raw:irc:join begin
[05:50:54] triggered bind *join:notes begin
[05:50:54] triggered bind *join:notes total time = 0.003ms
[05:50:54] triggered bind *raw:irc:join total time = 0.060ms
[05:50:54] triggered bind *raw:irc:368 begin
[05:50:54] triggered bind *raw:irc:368 total time = 0.012ms
[05:50:54] triggered bind *raw:irc:349 begin
[05:50:54] triggered bind *raw:irc:349 total time = 0.004ms

2018-08-23 16:20 UTC, thommey requested changes
I think that was before we discussed C89. Variable declarations must be moved up (the timevals).
Can we use clock_gettime(CLOCK_MONOTONIC) instead so this isn't affected by clock jumps? Maybe only count CPU time? Not sure, open for suggestions.

2018-08-25 02:22 UTC, michaelortmann commented
i moved the following questions a had over from #201:

pls come up/step forward with a concept answering 4 questions:

1st: where exactly we should log this
debugx() ?
putlog() ?
additional debug log file?

2nd: how to enable/disable that logging
console flags ?
(new) eggdrop.conf setting(s) ?
currently there is no option to enable/disable this performance logging, and it is output for console +d

3rd: what to log
only external tcl procs ?
also builtin procs ?

4th: real time or cpu time ?

2018-08-28 03:44 UTC, michaelortmann commented
**@thommey:** your requested changes are committed

2018-08-28 20:48 UTC, thommey reviewed
+d debug logging should be ok

2018-08-28 20:48 UTC, thommey commented on src/tclhash.c
> +    debug1("triggered bind %s start", proc);
I would suggest "triggering bind %s"

2018-08-28 20:48 UTC, thommey commented on src/tclhash.c
> +    debug2("triggered bind %s end time = %.3fms", proc,
I would suggest "triggered bind %s, duration = %.3fms"

2018-08-28 20:48 UTC, thommey commented on src/tclhash.c
> +    r = clock_gettime(CLOCK_MONOTONIC, &tp1);
CPU time is better

2018-09-17 19:26 UTC, michaelortmann commented
@thommey:

i changed the wording as requested

but i don't think we can/should use clock_gettime() with CLOCK_*_CPUTIME_ID

because despite clock_gettime() being posix 2001, CLOCK_*_CPUTIME_ID is not really, some operating systems don't have this (minix) and others implemented it first in year 2013 (openbsd).

i don't feel good using it and i don't have a replacement to offer for those systems lacking it.

besides its unclear from the text in issue #201, what the opener of the issue expects here, could expect CPU time, but could also expect other time.

2018-09-17 19:28 UTC, thommey commented
The issue was mostly raised about CPU time, because we have no way of accounting for resource usage of particular scripts. How about getrusage()?

2018-09-17 19:29 UTC, michaelortmann commented
sure clock() getrusage()... i throw them over board before, but now theire in again :)

2018-09-17 19:32 UTC, thommey commented
Interesting point. I think actual Tcl procs (those not starting with '*') would be enough for now

2018-09-17 19:36 UTC, thommey commented
The original report was filed, because it is difficult or impossible to track down Eggdrops using a lot of CPU time by script. Tcl retains no association between "script file" and procs, there is no real concept of "script file" (some [info] commands apparently retain it but not on the level we need and not backwards compatible).

We can exclude internal binds (all procs starting with '*') for now.

Logging per call seems fine for now, instead of aggregating and complicated statistics tracking, but that would certainly be an option for the future. getrusage() sounds appropriate to me.

2018-09-17 20:50 UTC, michaelortmann commented
@thommey: its done, take a look.

2018-09-17 20:59 UTC, michaelortmann commented
@thommey: its done, take a look.

2018-10-08 20:49 UTC, Cizzle commented
LGTM

2018-10-14 00:50 UTC, vanosg commented
build

2018-10-14 13:35 UTC, thommey approved these changes

2018-10-15 01:55 UTC, merged