Sunos
eggheads/eggdrop pull request #581
Opened 2018-08-26 03:02 UTC by michaelortmann

Found by: michaelortmann
Patch by: michaelortmann
Fixes: small issues found while compiling on sunos

One-line summary:
silence some sunos compiler warnings and clean up code

Additional description (if needed):
see commit messages below

Test cases demonstrating functionality (if applicable):
small test, start eggdrop, pid is displayed fine here:
./eggdrop
[...]
Launched into the background  (pid: 18138)

2018-09-09 16:39 UTC, thommey requested changes

2018-09-09 16:39 UTC, thommey commented on src/dcc.c
> +  egg_snprintf(digest_string, 33, "<%lx%x@", (long) getpid(),
%lx would correspond to unsigned long, right?

2018-09-15 19:46 UTC, michaelortmann commented
there is no such sing as "signed hex", so i use %lx for signed long as well as unsigned long. i guess every compiler will do the right thing. if i would cast (unsigned long) instead of (long) the code could be wrong, if the long is negative. which of course, wont ever happen with getpid(). maybe, it could happen, if microsoft invented their own getpid_s() ;)

so after reviewing my code, i still guess its correct.

but as always, if i error, if i didnt understand the problem, explain again pls.

2018-09-16 10:53 UTC, thommey commented
Ah, right. pid_t is signed, forgot about that, all good.

2018-09-16 10:53 UTC, thommey approved these changes

2018-09-16 19:43 UTC, merged