Add port and TLS info as a separate list item for tcl dcclist.
eggheads/eggdrop pull request #584
Opened 2018-08-26 21:11 UTC by Cizzle

Found by: Cizzle
Patch by: Cizzle
Fixes: Suggestion 2 at #155 

One-line summary: Adds the port and possible TLS info as a separate list item to tcl `dcclist`.

2018-10-14 13:41 UTC, thommey requested changes
LGTM but needs to be adjusted to show '-' after #552

2019-06-26 15:24 UTC, vanosg commented
#552 closed, OBE.

2019-08-18 10:11 UTC, thommey approved these changes

2019-08-24 22:51 UTC, Cizzle commented
Code doing the same was aded in commit b29d8b6 so after unconflicting there isn't that much left to do.

2019-08-25 01:58 UTC, merged