Define sizeof userfile at the right place
eggheads/eggdrop pull request #704
Opened 2018-10-14 22:21 UTC by michaelortmann

Found by: michaelortmann
Patch by: michaelortmann
Fixes: 

One-line summary:
Define sizeof userfile at the right place

Additional description (if needed):
Fixes compiler warning (3) in #703
Fixes magic number in commit 9e6f2790f10dff7f38cbfeaf30acb2e14e89b517
Add some comments

Test cases demonstrating functionality (if applicable):

2018-12-09 15:24 UTC, thommey requested changes

2018-12-09 15:24 UTC, thommey commented on src/userrec.c
> +  char new_userfile[sizeof userfile + 4]; /* 4 = sizeof "~new" */
at least the comment is misleading, 4 = strlen("~new"), 5 = sizeof("~new")

2018-12-10 03:42 UTC, michaelortmann commented on src/userrec.c
> +  char new_userfile[sizeof userfile + 4]; /* 4 = sizeof "~new" */
ty, fixed.

2018-12-10 22:04 UTC, Cizzle commented on src/main.c
> +  char s[sizeof userfile + 4]; /* 4 = sizeof "~bak" */
Same comment applies here.

2018-12-11 05:34 UTC, michaelortmann commented on src/main.c
> +  char s[sizeof userfile + 4]; /* 4 = sizeof "~bak" */
Done.

2019-08-18 09:58 UTC, thommey commented
Is defining it in a headerfile really the way to go? It seems unconventional and could define the symbol in multiple translation units without them being related. I don't think this is the right general solution for the issue of all those char arrays.

2019-08-26 22:46 UTC, michaelortmann commented
Thank you thommey, i committed a new/better solution, where i moved the function backup_userfile() from main.c to userrec.c.

2019-09-08 19:02 UTC, thommey approved these changes

2019-09-08 19:18 UTC, merged