Cleanup btos()
eggheads/eggdrop pull request #856
Opened 2019-08-28 19:56 UTC by michaelortmann

Found by: michaelortmann
Patch by: michaelortmann
Fixes: 

One-line summary:
Enhance / harden string handling by ripping out some sprintf() with array.

Additional description (if needed):
The function could be cleaned up much further, but my intention was not to waste too much time on it, but to enhance / harden string handling in general.

Test cases demonstrating functionality (if applicable):
Generate some traffic, then:
```
.traffic
[21:47:50] tcl: builtin dcc call: *dcc:traffic -HQ 1 
Traffic since last restart
==========================
IRC:
  out: 143 Bytes (143 Bytes today)
   in: 1.92 KBytes (1.92 KBytes today)
Partyline:
  out: 0 Bytes (0 Bytes today)
   in: 31 Bytes (31 Bytes today)
---
Total:
  out: 143 Bytes (143 Bytes today)
   in: 1.95 KBytes (1.95 KBytes today)
```

2019-09-29 17:16 UTC, thommey requested changes

2019-09-29 17:16 UTC, thommey commented on src/cmds.c
> +  char *unit;
const char :-)

2019-10-06 02:43 UTC, michaelortmann commented on src/cmds.c
> +  char *unit;
done :)

2019-10-06 02:44 UTC, michaelortmann reviewed
Ready for review again.

2019-11-02 16:57 UTC, thommey approved these changes
LGTM

2019-11-02 16:58 UTC, merged